name: GitHub Envs

run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on: 
  - workflow_dispatch

jobs:
  github-envs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "check GITHUB_ACTOR ${{ github.env.GITHUB_ACTOR }}, $GITHUB_ACTOR env."
      - run: echo "check GITHUB_REPOSITORY ${{ github.env.GITHUB_REPOSITORY }}, $GITHUB_REPOSITORY env."
      - run: echo "check GITHUB_WORKFLOW ${{ github.env.GITHUB_WORKFLOW }}, $GITHUB_WORKFLOW env."
      - run: echo "check GITHUB_USER ${{ github.env.GITHUB_USER }}, $GITHUB_USER env."