name: Matrix Job

on:
  - workflow_dispatch

jobs:
  example_matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest, macos-latest]
      max-parallel: 2
    steps:
      - run: echo "üêß This job is now running on a ${{ matrix.os }} server with ${{ matrix.version}}"
      - run: echo "${{ github.env}}"